### ISSUE TITLE
更改播放模式使游戏延迟设置改变

### ISSUE THREAD

**Issue by Dalieba0502** [2394425147/astrodx#104]
**Describe the bug**
调了半天延迟，换了一条耳机又不对了。调好了外放玩，延迟又双叒叕不对了。延迟调的头疼

**To Reproduce**
1.插入有线耳机，更改延迟设置使游戏正常游玩
2.拔出耳机，使用平板扬声器外放，上一步的延迟设置失效

**Expected behavior**
我希望插入耳机和外放的延迟一直都一样

**Screenshots**
nope

**Device specs**
 - Device: [iQOO pad]
 - OS: [android 14]
 - Version [DPD2307D_A_14.1.7.10.W10.V000L1]

**Additional context**

**Comment by charassss** [comment]
我认为可以更改需求为增设不同的延迟预设
