### ISSUE TITLE
Broken slides in practice mode

### ISSUE THREAD

**Issue by Himori-0** [2394425147/astrodx#109]
**Describe the bug**
Broken slides and star stuck on screen

**To Reproduce**
1. Go into practice mode
2. Go to a part with lots of slide
3. While playing retry when there's slides on screen

**Expected behavior**
A normal looking slide

**Screenshots**
![Screenshot_2024-06-16-10-00-00-159_com.Reflektone.AstroDX.jpg](https://github.com/2394425147/astrodx/assets/81427583/56e085e9-2220-4085-a6c2-66e53a4f4457)

**Device specs**
 - Device: Poco M4 Pro 5G
 - OS: HyperOS 1.0.1.0 Global
 - Version: 2.0.0 beta 1

**Additional context**
Fumi you should get some sleep.
Also the yellow star was there from the start of the practice to the end of the song 😀

**Comment by 2394425147** [comment]
Should be fixed in patch 1!
