### ISSUE TITLE
[Enhancement] Android Game Mode

### ISSUE THREAD

**Issue by I21b** [2394425147/astrodx#113]
Make [Game Dashboard](https://developer.android.com/games/gamedashboard/aboutdashboard) available. (Optimize performance)
[Documents](https://developer.android.com/games/optimize/adpf/gamemode/gamemode-api) [Sample](https://github.com/android/games-samples/tree/main/agdk/game_mode)

**Comment by DavidScann** [comment]
I'm going to be honest, why should we need this? It's not like AstroDX is a game that needs every bit of performance to be squeezed out from it.

Also, for stock based Android devices, you can add the application manually and it'll run with Game Mode.

**Comment by DavidScann** [comment]
![Screenshot_20240623-211215](https://github.com/2394425147/astrodx/assets/53106687/21aebe2e-88c4-47f9-b9b0-9813068b9f80)

Example given.
