### ISSUE TITLE
Upgrading from Pre-Beta to Beta Incorrectly Sets Most Song Scores to 5 Stars

### ISSUE THREAD

**Issue by VenB304** [2394425147/astrodx#124]
**Describe the bug**
The vast majority of Best scores in Song Select are currently set 5 Stars even if the accuracy is bad

**To Reproduce**
- Im not exactly sure if this happens to others too but the following is just how I think it happened

1. Set some scores in v2.0.0.beta.pre.99.exp.19
2. Update to Beta 2
3. Start migration 
4. ~~profit~~ inspect the scores in song select

**Expected behavior**
Correct Star count

**Screenshots**
![Screenshot_20240716-105846](https://github.com/user-attachments/assets/79295d50-eb54-4f5b-bd8d-3b4fd35d36da)
![Screenshot_20240716-123301](https://github.com/user-attachments/assets/f20d6af0-7b87-49c7-897d-c8ef79d6af69)
![Screenshot_20240716-123320](https://github.com/user-attachments/assets/b4916073-993f-463a-8e0d-082a034561e5)
![Screenshot_20240716-123405](https://github.com/user-attachments/assets/42d721e0-2209-46a4-b5cb-233fd479a61a)

**Device specs**
 - Device: Infinix Note 30 5G
 - OS: XOS v13.0.0
 - Version: Android 13

**Additional context**

**Comment by 2394425147** [comment]
Should be fixed in Beta 2 Patch 2, give it a shot!

**Comment by VenB304** [comment]
Yep, tried the terrifyingly fast update and it seems to work nicely now, thank you. I'm closing this then.
