### ISSUE TITLE
找不到/0/Android/data下的adx路径

### ISSUE THREAD

**Issue by RaTaiHok** [2394425147/astrodx#128]
如图，左边是data，右边是obb，obb有adx但是data没有![Screenshot_20240729_120511.jpg](https://github.com/user-attachments/assets/94546cc6-32ad-4101-bd8b-d17eb49c4bac)

设备:iqoo 12
系统:OriginOS 14, Android14-11
ADX版本: v2.0.0 beta2 patch5

**Comment by RaTaiHok** [comment]
草抱歉没看到要用英文提问
Im so sorry😔

**Comment by xhayper** [comment]
Please provide an English translation.
请提供英文翻译。

**Comment by RaTaiHok** [comment]
> Please provide an English translation. 请提供英文翻译。

Then I'll briefly describe it again

After installing ADX, I tried to find the adx file directory under ```/storage/imulated/0/Android/data```, but I couldn't find it. At first, I thought it was a problem with the file manager, but by executing the ```ls - a/storage/imulated/0/Android/data``` command, I found that this directory does not exist. However, there is ADX directory in ```storage/imulated/0/Android/obb```

I tried using my old phone (Android 9) to copy the same version of the adx directory to the data folder, and it showed that the directory already existed. I chose whether to overwrite it or not

I am very puzzled about this

Device: Vivo IQOO 12
System: OriginOS 14/Android 14-11
ADX version: v2.0.0 beta2 patch5

**Comment by xhayper** [comment]
Have you run AstroDX once after installing?

**Comment by RaTaiHok** [comment]
> Have you run AstroDX once after installing?

yeah i have run it once

**Comment by xhayper** [comment]
Maybe this can help you out
https://astrodx.notion.site/AstroDX-73b5ccf4f9634eed9ee11468a47c0855

**Comment by RaTaiHok** [comment]
> Maybe this can help you out https://astrodx.notion.site/AstroDX-73b5ccf4f9634eed9ee11468a47c0855

ah,this is exist
![QQ_1722234684552](https://github.com/user-attachments/assets/849b5ebe-e962-4dbd-b391-50ccaf9582a6)
But my charts files are all on my phone, so importing them through adb is a bit troublesome
I'll slowly import it myself
Thank you for your answer

**Comment by 2394425147** [comment]
If you're running 2.0.0 Beta 2 Patch 5 or above, you can just change the extension of the chart zip file to .adx, and you'll be able to open it up with astrodx directly
Give that a try sometime!

如果你的astrodx版本在2.0.0 Beta 2 Patch 5或以上的话，你可以直接把谱面包的扩展名.zip改成.adx，就可以直接通过astrodx打开了
有机会的话可以试试！

**Comment by RaTaiHok** [comment]
> If you're running 2.0.0 Beta 2 Patch 5 or above, you can just change the extension of the chart zip file to .adx, and you'll be able to open it up with astrodx directly Give that a try sometime!
> 
> 如果你的astrodx版本在2.0.0 Beta 2 Patch 5或以上的话，你可以直接把谱面包的扩展名.zip改成.adx，就可以直接通过astrodx打开了 有机会的话可以试试！

it works, so cool, thx
