### ISSUE TITLE
Use practice mode when ending the game results in abnormal scores (beta1 patch7)

### ISSUE THREAD

**Issue by Nekowryyy** [2394425147/astrodx#137]
Astrodx 2.0.0 beta1 patch7
Enter practice mode after the end (skip appears in the lower right corner)
After playing for a while, I came out and found that the accuracy rate of the practice mode was added to the total accuracy rate and saved it.

**Comment by Nekowryyy** [comment]
![Uploading IMG_20240820_234211.jpg…]()

**Comment by 2394425147** [comment]
这个问题在beta 2解决了，可以更新到patch 5试试看
