### ISSUE TITLE
The new level importing method sucks.

### ISSUE THREAD

**Issue by NsCrosu** [2394425147/astrodx#138]
we could just drop tons of levels with already existing catalog BEFORE Beta2 Patch 4.
but now we can only waiting for make a 11GiB zip file, waiting it transport to device, waiting file manager transport the file to the app, waiting the app decompress the zip file.
and then telling me that only 2GB file max is supported.

why would you make this change? who wants a song in two folders? we all love collections for game versions and we dont want a complicated and cumbersome importing method for tiny benifit. and i wasted 40 minutes just for practice mode.

**Comment by NsCrosu** [comment]
please enhance the wired logic now. or make a compat for old level files🙏

**Comment by DavidScann** [comment]
I'll address these issues one by one, hopefully you'll be satisfied with these answers.
1. The fact that you had to do this manually proves that either something went wrong with the automatic migration, or you just wanted to do it manually. Regardless, it should be as easy as changing the extension from .zip to .adx, then opening it with AstroDX. Nothing should've been done manually.
2. We're not at fault for your failure of making a zip file archive. There are programs out there that helps you do this on your device; I have no idea which one you've used that limited you to 2GB, but none of the apps that I've used so far has done this.
3. As for the why, [read this section.](https://www.notion.so/astrodx/Installation-Guide-for-Android-3f2ec5041ad5413ab45500472bb4ceba?pvs=4#b84dabeec01b44a7b297631fa7d0a1c6)
4. I just wanted to say, reading this issue felt incredibly rude. It's not intolerable, but please be aware of how you word things going into the future.

**Comment by 2394425147** [comment]
There's actually a lot more planned besides allowing the same level to be used in multiple collections. I'll spare you the details but this is indeed necessary.

To fix your issue, you should probably package each collection into an adx archive, and import them individually.

**Comment by NsCrosu** [comment]
I apologize for my inappropriate words earlier, I was just a little annoyed at the time that I said something that wasn't very respectful, please forgive me.
There are some misunderstandings I would like to clear up.

1. I did get the .adx file by renaming the .zip file.
2. I saved the file originally on my PC because it was too large.
2.1 I didn't compress the .zip files because I didn't need them before, and it was easier for me to get and change the txt files or something else.
3. in versions before Patch 4, I only had to wait `once` to `transfer the data to the levels folder`.
3.1 And now I first need to compress the 11GiB files to zip (adx) on PC (which requires waiting)
3.2 Then move this file to the device (wait *2)
3.3 Then I need to choose to open it with AstroDX in the file manager on the device, and since there is only one copy of the file, the file manager will extract a copy of the .adx file to distribute to the AstroDX program (wait *3)
3.4 AstroDX program will decompress (or read, I don't know) the file (wait *4)
4. Finally, after waiting for a long white screen, an error log pops up at the bottom of `AstroDX's` screen stating that the maximum file import limit is 2 gigabytes, that the import failed, and that I didn't get levels up to at least 2 gigabytes.

Comparing this to versions prior to Patch 4, I waited close to 40 minutes to reach the original result, whereas originally I only had to wait once for `3.2`, which only took about 10 minutes.
Not to mention that the file manager extraction and app decompression required double the cache space to staging the files during this time, and it's not clear to me that I need to manually delete the .adx file again to free up the extra 11GiB of space it's taking up.

Again, I apologize for my previous inappropriate comments, I was just a bit impulsive.

Translated with DeepL.com (free version)
