### ISSUE TITLE
New Record Score Cannot be Recorded. 

### ISSUE THREAD

**Issue by WilliamRiker01** [2394425147/astrodx#143]
**Describe the bug**
在一首歌打出新纪录之后，无法被记录上。
After a song score hits a new record, it can't be recorded.
**Device specs**
 - Device: [e.g. iPad 9]
 - OS: [e.g. iOS17.6.1]

![bcf2910b1e0335c7230dbb0035bb5d3d](https://github.com/user-attachments/assets/002afe32-7621-4aa1-92d6-283b3708996c)
打完一首歌后，该歌曲分数为最新记录。
After playing a song, the score of the song is the latest record, higher than the former one. 
![04e0b3c615eca5defb5f095acebdf84a](https://github.com/user-attachments/assets/af7a6363-042a-4dbb-81cc-00d4e852b406)
但回到主界面后歌曲成绩没有记录。
However, after returning to the main interface, the song score is not recorded.

**Comment by 2394425147** [comment]
You should turn off the timewarp mod in mods, having it on prevents you from setting scores.

add.:
You probably used practice mode in a prior play, this automatically enables timewarp and doesn't turn it off automatically. We're fixing this issue right now, so it should be resolved very soon.
