### ISSUE TITLE
cache migration encounters issues with "maidata.txt" due to being case sensitive

### ISSUE THREAD

**Issue by HDEnt327** [2394425147/astrodx#144]
**Describe the bug**
During cache migration phase, when the charts are being accessed, certain charts that do not exactly match "maidata.txt", e.g. "MaiData.txt", which (previously) does work when playing the chart, causes an error and the entire process is halted. The chart directory thus must be manually deleted, and the program needs to be reopened for the cache migration to continue.
Although the file name convention is usually to name the chart file "maidata.txt" instead of "MaiData.txt", it previously does work and many charts do use the latter form of capitalization, this causes the migration process to be troublesome.

**To Reproduce**
1. Have a old version of AstroDX installed before updating to the latest version
2. Have chart directories which contain "MaiData.txt" instead of "maidata.txt"
3. Start the cache migration process in game

**Expected behavior**
Charts should be successfully migrated regardless of the capitalization formatting, instead of the program halting when one is encountered.

**Screenshots**
![微信图片_20240916171600](https://github.com/user-attachments/assets/2ce37977-95dd-46c8-9238-7b8dd2ca84c5)
![微信图片_20240916171637](https://github.com/user-attachments/assets/b9f0e76c-783e-4058-a02e-b3e1370c600f)
These files previously **DOES WORK IN GAME**

**Device specs**
 - Device: iPad Pro (3rd gen)
 - OS: iOS 17.6.1
 - AstroDX Testflight Version 2.0.1 (1)

**Additional context**

**Comment by 2394425147** [comment]
should be fixed by the next update! thanks for the issue
