### ISSUE TITLE
Practice mode with repeatable sections

### ISSUE THREAD

**Issue by Zhuym07** [2394425147/astrodx#62]
**Is your feature request related to a problem? Please describe.**
练习某些交互时想重复练习某段，只能重开一盘新游戏之后重复打前面的部分
**Describe the solution you'd like**
添加重复练习功能，类似英语磁带的重复某句
以下为UI举例

![image](https://github.com/2394425147/maipaddx/assets/34023479/e3312738-4ced-4721-9851-4bf562fdcb82)

**Comment by nanwy** [comment]
哈嘍 想問一下這個功能實裝了嗎 看狀態是closed了🥹
