### ISSUE TITLE
Autoplay with All Good option, didn't result in All Good, instead it is All Great

Steps
1. Activate Autoplay
2. Change settings to All Good
3. Play a chart till the end
4. Result will be All Great instead of All Good

Expected Behaviour
1. All hits should be Good

### ISSUE THREAD

**Issue by Alsen99** [2394425147/astrodx#89]
![Screenshot_2024-04-03-12-27-08-991_com.Reflektone.AstroDX.jpg](https://github.com/2394425147/astrodx/assets/54655737/6cde4e54-d1f5-47d6-b8cf-7ef6452c3908)

![Screenshot_2024-04-03-12-23-59-260_com.Reflektone.AstroDX.jpg](https://github.com/2394425147/astrodx/assets/54655737/3fea5b59-eccc-4c06-8bce-9d159c706d4a)

**Device specs**
 - Device: Xiaomi 11T
 - OS: MIUI 14 
 - Chrome
 - 2.0.0.beta.pre.99.exp.19

**Comment by 2394425147** [comment]
Fixed in the next version, keep an eye out for it 👀
