### ISSUE TITLE
分裂星的星星头必须点两次

### ISSUE THREAD

**Issue by shiawasenahikari** [2394425147/astrodx#94]
星雫（ホシシズク）红谱的 174combo 处是由一个星星头分裂成两个星星的配置，虽然谱面中实际是两个星星头，但在实体机上打只需要拍一次星星头就能直接加两个 combo，但是在板子上打反而得连拍两次星星头。如图所示
![IMG_0002](https://github.com/2394425147/astrodx/assets/32567875/3b249095-37f4-47d6-a66f-b9262620fc8c)

**Comment by 2394425147** [comment]
可以分享谱面里面相关的小节吗

**Comment by shiawasenahikari** [comment]
https://github.com/2394425147/astrodx/assets/32567875/f8c2bd3d-c34c-4ef5-8653-a7ae43d52489

**Comment by 2394425147** [comment]
不好意思，我其实想说maidata.txt文件里面的那一个小节的
这个属于正常的simai语法，在实现星星的时候是仔细测试过的，所以大概率是谱面有误写

**Comment by shiawasenahikari** [comment]
我找到了那一小节的文本

{4}3h[4:1],1,3,42,{1}3V14[2:1]/3pp4[2:1],

**Comment by 2394425147** [comment]
对的，最后那个星星应该是`3V14[2:1]*pp4[2:1]`而不是`3V14[2:1]/3pp4[2:1]`
