### ISSUE TITLE
File initialization exception

### ISSUE THREAD

**Issue by NK1Gone** [2394425147/astrodx#97]
**Describe the bug**
Xiaomi HyperOS AstroDX initialization files in a directory path for/Android/obb/com. Reflektone. AstroDX, not in/Android/data/com Reflektone AstroDX, lead to can't normal import pavement

**To Reproduce**
1.Shizuku authorized mt file manager root could not find the file directory

**Expected behavior**
Let Xiaomi HyperOS can be imported into the pavement normally after root

**Screenshots**
![Screenshot_2024-05-07-16-00-39-953_com Reflektone AstroDX](https://github.com/2394425147/astrodx/assets/111185712/591c14f5-08e9-4e0b-8345-c5202744463f)

https://github.com/2394425147/astrodx/assets/111185712/4553062d-2b44-4617-a3a3-3d86df4e2231

**Device specs**
 - Device: Xiaomi14
 - OS: HyperOS 
 - Version: 1.0.24.4.22.DEV by Android14

**Additional context**
Only hyperos devices are affected. MIUI systems are not affected

**Comment by NK1Gone** [comment]
OMG，The hidden directory can be displayed through the command, but any file manager can not display the page, I need to test whether the import shop through the command can play normally.
![Uploading Screenshot_2024-05-09-11-42-27-612_bin.mt.plus-edit.jpg…]()

**Comment by NK1Gone** [comment]
This can be solved by using the rish shell command to copy into the levels folder. 
![Screenshot_2024-05-09-13-53-43-602_bin mt plus-edit](https://github.com/2394425147/astrodx/assets/111185712/cfd51d98-ffad-43a5-be44-4deb1cb6ec87)
![Screenshot_2024-05-09-13-32-02-503_com Reflektone AstroDX](https://github.com/2394425147/astrodx/assets/111185712/ec5194aa-8a63-4eb8-8b35-3cc1f0c76c5c)

**Comment by DavidScann** [comment]
Yep, this is an Android bug alright.

If you feel that this issue has been resolved, please close the issue.
